name: Auto Pull Request

on:
  schedule:
    - cron: "0 1,9,17 * * *"  # Jalan 3x sehari
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "ammangdzaky"
          git config user.email "abdurrahmandzaky01@gmail.com"

      - name: Install GitHub CLI
        uses: cli/gh-action@v2  # INI YANG PENTING

      - name: Buat Branch & PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="auto-pr-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          echo "Update: $(date)" >> pr-log.txt
          git add pr-log.txt
          git commit -m "🤖 Auto PR: $(date)"
          git push origin "$BRANCH_NAME"

          gh pr create \
            --base main \
            --head "$BRANCH_NAME" \
            --title "🤖 Auto PR: $(date)" \
            --body "PR otomatis dari GitHub Actions"
