name: Auto Commit

on:
  schedule:
    - cron: "0 */2 * * *"  # Tiap 2 jam UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "ammangdzaky"
          git config user.email "abdurrahmandzaky01@gmail.com"

      - name: Update file & commit
        run: |
          echo "Update: $(date)" >> commit-log.txt
          git add commit-log.txt
          git commit -m "🕒 Auto commit: $(date)" || echo "No changes to commit"
          git push origin main
