name: Auto Pull Request

on:
  schedule:
    - cron: "0 */4 * * *"  # Tiap 4 jam UTC
  workflow_dispatch:

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "ammangdzaky"
          git config user.email "abdurrahmandzaky01@gmail.com"

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Buat Branch & PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="auto-pr-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          echo "Update: $(date)" >> pr-log.txt
          git add pr-log.txt
          git commit -m "🤖 Auto PR: $(date)"
          git push origin "$BRANCH_NAME"

          gh pr create \
            --base main \
            --head "$BRANCH_NAME" \
            --title "🤖 Auto PR: $(date)" \
            --body "Closes #${{ github.run_number }}\n\nPR otomatis dari GitHub Actions"
